import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as THREE from '../vendor/three.module.js';
import { GLTFLoader } from '../vendor/GLTFLoader.js';
import { prepareMork, makeMork } from '../src/mork.js';
import { applyTankFeel, applyTankHealth } from '../src/tankfeel.js';
import { applySecondaryToe, secondaryPivots } from '../src/units.js';

const bytes = readFileSync(new URL('../assets/models/hover-tank/mork_hover_tank_d0.glb', import.meta.url));
const gltf = await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), '');
const source = prepareMork(gltf.scene, gltf.animations);
assert.equal(source.stats.triangles, 24196);
assert(source.stats.batches < 70);
const a = makeMork(source), b = makeMork(source);
for (const clip of gltf.animations) for (const track of clip.tracks)
  assert(a.getObjectByName(THREE.PropertyBinding.parseTrackName(track.name).nodeName), track.name);
const feel = { t: 0, hoverT: 0, recoil: 0 };
applyTankFeel(a, feel);
assert(Math.abs(a.getObjectByName('HOVER_RIG').position.y) < 1e-5);
applyTankFeel(a, { ...feel, t: 2, hoverT: 1 });
assert(a.getObjectByName('HOVER_RIG').position.y > 0.5);
applyTankFeel(a, { ...feel, t: 3, hoverT: 1, recoil: 0.2 });
applyTankFeel(a, { ...feel, t: 3.1, hoverT: 1, recoil: 0.1 });
assert(a.getObjectByName('GUN_RECOIL').position.z < -0.7);
applyTankFeel(a, { ...feel, t: 5 });
assert(Math.abs(a.getObjectByName('GUN_RECOIL').position.z) < 1e-5);
assert(Math.abs(a.getObjectByName('HOVER_RIG').position.y) < 1e-5);
const lens = g => { let material; g.getObjectByName('AMMO_PORT_LIGHT_08').traverse(o => { if (o.isMesh) material = o.material; }); return material; };
const heat=a.userData.heatSleeve;
assert(heat?.isMesh && heat.material.isMeshBasicMaterial);
assert.equal(heat.material.color.getHex(),0x232833);
heat.material.color.setHex(0xff2a10);
assert.equal(b.userData.heatSleeve.material.color.getHex(),0x232833);
assert.equal(heat.name,'Long_cannon_barrel');
assert(a.getObjectByName('GUN_RECOIL').getObjectById(heat.id));
a.userData.setAmmo(0);
assert.equal(lens(a).emissiveIntensity, 0);
assert.equal(lens(b).emissiveIntensity, 2);
assert(a.userData.healthBeam.length > 0);
applyTankHealth(a, 0);
assert(a.userData.healthBeam[0].emissive.r > a.userData.healthBeam[0].emissive.b);
assert.notEqual(a.userData.healthBeam[0].emissive.getHex(), b.userData.healthBeam[0].emissive.getHex());
a.userData.tick(1);
assert(a.getObjectByName('TURRET_YAW').rotation.y !== 0);
applySecondaryToe(a, 0.1);
assert(secondaryPivots(a).every(p => Math.abs(Math.abs(p.rotation.y) - 0.1) < 1e-6));
assert.equal(a.userData.laserGuns.length, 2);
assert(a.userData.muzzle.getWorldPosition(new THREE.Vector3()).toArray().every(Number.isFinite));
a.userData.dispose();
assert(makeMork(source).userData.muzzle);
console.log(`MÖRK pinned rig, power/recoil, actual sockets, independent ammo and toe pass: ${JSON.stringify(source.stats)}`);
