import assert from 'node:assert/strict';
import { hexDigits, glyphArcs, glyphValue } from '../src/domain/score-glyphs.js';
assert.deepEqual(hexDigits(0), [0]); assert.deepEqual(hexDigits(15), [15]); assert.deepEqual(hexDigits(256), [0, 0, 1]); assert.deepEqual(hexDigits(0x1a3), [3, 10, 1]);
assert.deepEqual(glyphArcs(0), { arcs: [], dot: true, rings: 1 }, 'zero alone is a centre dot');
assert.equal(glyphArcs(3).arcs.length, 2, '3 is the upper semicircle: two arcs'); assert.ok(glyphArcs(3).arcs.every((a) => a.to <= Math.PI && a.from >= 0), 'both in the upper half');
assert.equal(glyphArcs(15).arcs.length, 4, '15 is a full ring');
const g = glyphArcs(0x2f, { radius: 1, step: 0.2 });
assert.equal(g.rings, 2); assert.ok(g.arcs.filter((a) => a.digit === 0).every((a) => a.r === 1) && g.arcs.filter((a) => a.digit === 1).every((a) => Math.abs(a.r - 0.8) < 1e-9), 'the units place is the outer ring');
for (const n of [1, 2, 4, 8, 7, 12, 100, 4095, 60000]) assert.equal(glyphValue(glyphArcs(n).arcs), n, `${n} reads back`);
console.log('Score glyphs: quarter-circle base-16 digits, units outermost, zero a dot, every number reads back.');
