// What Isao says on screen and has never said aloud, as a recording script in the seiyu_voice format (owner, 2026-10-04: "we will
// record ALL the lines that Isao has that are not spoken yet"). Pure: the briefs, the recorded triggers and their index come in.
//
// Two parts. SILENT BRIEFS: a brief no recorded trigger answers, every line of it, its id the trigger (the voice wires itself to a brief
// by id, so a take of it needs no new hook). UNRECORDED TEXT: a brief that does speak, but whose on-screen words were never recorded
// (its takes are variations); those lines are listed under the trigger they would join. Each trigger heads one group only, because the
// seiyu_voice importer numbers a trigger's lines from its heading, and a bullet never carries a straight double quote, which it parses.

const words = (s) => String(s).toLowerCase().replace(/[^a-z0-9åäöüéè]+/g, ' ').trim();
const bullet = (s) => `- "${String(s).replace(/"([^"]*)"/g, '“$1”').replace(/"/g, '”').replace(/\s+/g, ' ').trim()}"`;

export function unvoicedScript({ briefs, triggers, index, date = '' }) {
  const silent = [], unrecorded = new Map();
  for (const [id, b] of Object.entries(briefs)) {
    const lines = (b.lines ?? []).filter((l) => typeof l === 'string' && l.trim());
    if (!lines.length) continue;
    const key = index.resolve(id);
    if (!key) { silent.push({ id, title: b.title ?? '', lines }); continue; }
    const said = new Set((triggers[key]?.lines ?? []).map((l) => words(l.text)));
    const missing = lines.filter((l) => !said.has(words(l)));
    if (!missing.length) continue;
    // a brief that only a wildcard answers (build_armory under build_*) gets its own trigger: an exact id outranks the wildcard
    const named = key === id || (triggers[key]?.aliases ?? []).includes(id), at = named ? key : id;
    const g = unrecorded.get(at) ?? { key: at, from: [], lines: [] };
    g.from.push(id);
    for (const l of missing) if (!g.lines.some((x) => words(x) === words(l))) g.lines.push(l);
    unrecorded.set(at, g);
  }
  const groups = [...unrecorded.values()];
  const count = silent.reduce((a, s) => a + s.lines.length, 0) + groups.reduce((a, g) => a + g.lines.length, 0);
  const md = [
    `# Isao's unvoiced lines — the recording script for what he shows and never says${date ? ` (${date})` : ''}`,
    '',
    'Generated by Stålheart (scripts/isao-unvoiced.mjs) from src/isaobriefs.js and the voice already recorded. Same voice, same rules as',
    'ISAO-VOICE-LINES.md: one breath a line, laconic; CAPS are shouted. Each trigger is the brief id the game already raises, so a take',
    'of it plays with no new wiring. Merge into ISAO-VOICE-LINES.md by hand: a trigger in part 2 joins the group it names there.',
    '',
    `${silent.length} silent briefs, ${groups.length} triggers with unrecorded on-screen text, ${count} lines.`,
    '',
    '---',
    '',
    '## 1. Silent briefs (nothing recorded)',
    '',
    ...silent.flatMap((s) => [`**trigger:** \`${s.id}\`${s.title ? ` (${s.title.replace(/[`*]/g, '')})` : ''}`, ...s.lines.map(bullet), '']),
    '## 2. Spoken briefs, words on screen never recorded',
    '',
    ...groups.flatMap((g) => [`**trigger:** \`${g.key}\` (shown as ${g.from.join(', ')})`, ...g.lines.map(bullet), '']),
    '### Notes for recording',
    '',
    '- Generated text: read it as written, or rewrite a line shorter in the script before rendering; the on-screen text stays the game\'s.',
    '',
  ].join('\n');
  return { md, silent: silent.length, triggers: groups.length, lines: count };
}
