// GENERATED by scripts/import-isao-voice.mjs from the seiyu_voice export (A-1, 2026-10-04T05:47:34Z); do not edit.
// Isao's recorded lines by trigger: 48 triggers, 155 lines. Files are assets/audio/isao/<id>.mp3, pinned in
// docs/isao-voice-audio.lock.json. `kind` is spoken, announce or countdown; `beats` are a countdown's number onsets in seconds from
// the file's start; `qualifier` is a game-side condition that is never spoken.
export const ISAO_VOICE_SOURCE = Object.freeze({ chain: "A-1", generated: "2026-10-04T05:47:34Z" });
export const ISAO_TRIGGERS = {
 "mission": {
  "aliases": [
   "mission"
  ],
  "note": "(src/fx/mission-card.js) — once, over the descent",
  "lines": [
   {
    "id": "mission_04",
    "text": "LAND. BUILD. PROTECT WHAT WE BUILT.",
    "kind": "announce",
    "duration": 2.942
   },
   {
    "id": "mission_05",
    "text": "BUILD. DEFEND. Connect to the Dyson sphere.",
    "kind": "spoken",
    "duration": 3.275
   },
   {
    "id": "mission_06",
    "text": "it's just us. we cannot fail.",
    "kind": "spoken",
    "duration": 2.528
   }
  ]
 },
 "rough_landing": {
  "aliases": [
   "rough_landing"
  ],
  "lines": [
   {
    "id": "rough_landing_01",
    "text": "Rough landing!",
    "kind": "spoken",
    "duration": 1.291
   },
   {
    "id": "rough_landing_05",
    "text": "DIDN'T even Crash.",
    "kind": "spoken",
    "duration": 1.568
   },
   {
    "id": "rough_landing_04",
    "text": "Rough landing.  I want a refund. ha ha.",
    "kind": "spoken",
    "duration": 3.125
   }
  ]
 },
 "so_much_to_build": {
  "aliases": [
   "so_much_to_build"
  ],
  "lines": [
   {
    "id": "so_much_to_build_01",
    "text": "So much to build.",
    "kind": "spoken",
    "duration": 1.653
   },
   {
    "id": "so_much_to_build_02",
    "text": "Empty planet. Full schedule.",
    "kind": "spoken",
    "duration": 2.357
   },
   {
    "id": "so_much_to_build_03",
    "text": "Right. Where do we start.",
    "kind": "spoken",
    "duration": 1.952
   }
  ]
 },
 "foundry_deploy": {
  "aliases": [
   "foundry_deploy"
  ],
  "lines": [
   {
    "id": "foundry_deploy_04",
    "text": "I'll Cannibalize our landing rocket.  that's protocol.",
    "kind": "spoken",
    "duration": 3.787
   },
   {
    "id": "foundry_deploy_05",
    "text": "There is no going back.",
    "kind": "spoken",
    "duration": 1.867
   },
   {
    "id": "foundry_deploy_06",
    "text": "Full control is our only way out of here.",
    "kind": "spoken",
    "duration": 3.147
   }
  ]
 },
 "sites_seen": {
  "aliases": [
   "sites_seen"
  ],
  "lines": [
   {
    "id": "sites_seen_05",
    "text": "The other rockets have valuable materials.",
    "kind": "spoken",
    "duration": 3.275
   },
   {
    "id": "sites_seen_06",
    "text": "Their cargo must become ours.",
    "kind": "spoken",
    "duration": 2.293
   },
   {
    "id": "sites_seen_03",
    "text": "See the beacons? Something worth fetching at each.",
    "kind": "spoken",
    "duration": 3.253
   },
   {
    "id": "sites_seen_07",
    "text": "Some landed.  Some Crashed.  All have something.",
    "kind": "spoken",
    "duration": 3.36
   }
  ]
 },
 "site_cleared": {
  "aliases": [
   "site_cleared",
   "part_home"
  ],
  "lines": [
   {
    "id": "site_cleared_01",
    "text": "Nest cleared. The part is yours.",
    "kind": "spoken",
    "duration": 2.357
   },
   {
    "id": "site_cleared_02",
    "text": "Bring it home. Carefully.",
    "kind": "spoken",
    "duration": 1.803
   },
   {
    "id": "site_cleared_03",
    "text": "Got it. I can print with that.",
    "kind": "spoken",
    "duration": 2.123
   },
   {
    "id": "site_cleared_05",
    "text": "Useful chips.  Ours now.",
    "kind": "spoken",
    "duration": 2.336
   }
  ]
 },
 "build_start": {
  "aliases": [
   "build_*",
   "printer"
  ],
  "note": "an order starts",
  "lines": [
   {
    "id": "build_start_01",
    "text": "Printing.",
    "kind": "spoken",
    "duration": 1.077
   },
   {
    "id": "build_start_02",
    "text": "On it.",
    "kind": "spoken",
    "duration": 1.056
   },
   {
    "id": "build_start_03",
    "text": "Give me a minute. Precision takes a minute.",
    "kind": "spoken",
    "duration": 2.933
   },
   {
    "id": "build_start_04",
    "text": "Layer by layer.",
    "kind": "spoken",
    "duration": 1.525
   },
   {
    "id": "build_start_05",
    "text": "Wireframe first. Then skin.",
    "kind": "spoken",
    "duration": 2.656
   }
  ]
 },
 "print_done": {
  "aliases": [
   "print_done"
  ],
  "lines": [
   {
    "id": "print_done_01",
    "text": "Done.",
    "kind": "spoken",
    "duration": 0.885
   },
   {
    "id": "print_done_02",
    "text": "Standing.",
    "kind": "spoken",
    "duration": 1.163
   },
   {
    "id": "print_done_03",
    "text": "Built to last. Mostly.",
    "kind": "spoken",
    "duration": 1.973
   },
   {
    "id": "print_done_04",
    "text": "Next.",
    "kind": "spoken",
    "duration": 0.992
   }
  ]
 },
 "build_gate": {
  "aliases": [
   "build_gate"
  ],
  "lines": [
   {
    "id": "build_gate_01",
    "text": "Gate first. Then walls.",
    "kind": "spoken",
    "duration": 2.229
   },
   {
    "id": "build_gate_03",
    "text": "The Gate opens automatically for you.  You're welcome.",
    "kind": "spoken",
    "duration": 3.659
   }
  ]
 },
 "stalheart_begins": {
  "aliases": [
   "stalheart_begins",
   "stalheart_stands"
  ],
  "lines": [
   {
    "id": "stalheart_begins_01",
    "text": "At the pole: the Stålheart. A terraformer. The only one.",
    "kind": "spoken",
    "duration": 4.064
   },
   {
    "id": "stalheart_begins_02",
    "text": "It does not defend itself. That part is us.",
    "kind": "spoken",
    "duration": 3.488
   },
   {
    "id": "stalheart_begins_03",
    "text": "The Stålheart stands. Your MÖRK is rolling out.",
    "kind": "spoken",
    "duration": 3.488
   },
   {
    "id": "stalheart_begins_05",
    "text": "The Stalheart builds the Tanks.  Don't crash them.",
    "kind": "spoken",
    "duration": 3.381
   }
  ]
 },
 "build_garage": {
  "aliases": [
   "build_garage",
   "paint_pad"
  ],
  "lines": [
   {
    "id": "build_garage_06",
    "text": "Pimp your ride.  You know you want it.",
    "kind": "spoken",
    "duration": 2.613
   },
   {
    "id": "build_garage_05",
    "text": "Exoplanets are boring without pink.",
    "kind": "spoken",
    "duration": 2.741
   },
   {
    "id": "build_garage_03",
    "text": "The hull has been grey long enough.",
    "kind": "spoken",
    "duration": 2.229
   },
   {
    "id": "build_garage_04",
    "text": "Hazard stripes? Bold.",
    "kind": "spoken",
    "duration": 2.08
   }
  ]
 },
 "manual_override": {
  "aliases": [
   "manual_override"
  ],
  "note": "(Rotor) — with the red ROTOR MANUAL OVERRIDE!",
  "lines": [
   {
    "id": "manual_override_01",
    "text": "ROTOR — MANUAL OVERRIDE!",
    "kind": "announce",
    "duration": 1.867
   },
   {
    "id": "manual_override_06",
    "text": "The chips aren't ready for auto-targeting.  Take over.",
    "kind": "spoken",
    "duration": 3.829
   },
   {
    "id": "manual_override_05",
    "text": "MANUAL CONTROL - LET HER RIP!",
    "kind": "announce",
    "duration": 2.016
   },
   {
    "id": "manual_override_07",
    "text": "They look hostile. Engage.",
    "kind": "spoken",
    "duration": 2.336
   }
  ]
 },
 "quiver_override": {
  "aliases": [
   "quiver_override"
  ],
  "note": "with QUIVER MANUAL OVERRIDE!",
  "lines": [
   {
    "id": "quiver_override_01",
    "text": "QUIVER — MANUAL OVERRIDE!",
    "kind": "announce",
    "duration": 1.845
   },
   {
    "id": "quiver_override_05",
    "text": "These creatures have harder cores.  dangerous.",
    "kind": "spoken",
    "duration": 3.381
   },
   {
    "id": "quiver_override_06",
    "text": "AIM. LOCK. Shoot.  easy.  I'll automate it soon.",
    "kind": "spoken",
    "duration": 3.509
   },
   {
    "id": "quiver_override_07",
    "text": "ONE ROUND AT A TIME.   Destruction guaranteed.",
    "kind": "spoken",
    "duration": 3.467
   }
  ]
 },
 "good_hit": {
  "aliases": [
   "good_hit"
  ],
  "lines": [
   {
    "id": "good_hit_01",
    "text": "Good hit.",
    "kind": "spoken",
    "duration": 1.141
   },
   {
    "id": "good_hit_02",
    "text": "Clean.",
    "kind": "spoken",
    "duration": 1.077
   },
   {
    "id": "good_hit_03",
    "text": "That's how it's done.",
    "kind": "spoken",
    "duration": 1.632
   }
  ]
 },
 "gunship_overhead": {
  "aliases": [
   "gunship_overhead",
   "gunship_pass"
  ],
  "lines": [
   {
    "id": "gunship_overhead_01",
    "text": "Gunship on station.",
    "kind": "spoken",
    "duration": 1.717
   },
   {
    "id": "gunship_overhead_02",
    "text": "KORP overhead. The guns are yours.",
    "kind": "spoken",
    "duration": 2.805
   },
   {
    "id": "gunship_overhead_04",
    "text": "Now I am become Death. The destroyer of critters.",
    "kind": "spoken",
    "duration": 3.588
   }
  ]
 },
 "mk9_release": {
  "aliases": [
   "TACTICAL NUKE LAUNCHED"
  ],
  "note": "the MK-9 release",
  "lines": [
   {
    "id": "mk9_release_01",
    "text": "TACTICAL NUKE LAUNCHED!",
    "kind": "announce",
    "duration": 1.739
   },
   {
    "id": "mk9_release_02",
    "text": "Say hello to my little bomb.",
    "kind": "spoken",
    "duration": 2.059
   },
   {
    "id": "mk9_release_06",
    "text": "They don't stand a chance.",
    "kind": "spoken",
    "duration": 1.76
   },
   {
    "id": "mk9_release_07",
    "text": "I say we nuke them from orbit. it's the only way.",
    "kind": "spoken",
    "duration": 3.501
   },
   {
    "id": "mk9_release_08",
    "text": "Ignition in 3 2 1",
    "kind": "spoken",
    "duration": 2.927
   }
  ]
 },
 "mk9_lands": {
  "aliases": [
   "mk9_lands"
  ],
  "lines": [
   {
    "id": "mk9_lands_01",
    "text": "Crater.",
    "kind": "spoken",
    "duration": 1.013
   },
   {
    "id": "mk9_lands_02",
    "text": "That'll leave a mark.",
    "kind": "spoken",
    "duration": 1.696
   },
   {
    "id": "mk9_lands_03",
    "text": "And they're gone.",
    "kind": "spoken",
    "duration": 1.483
   }
  ]
 },
 "gunship_calibrated": {
  "aliases": [
   "gunship_calibrated",
   "gunship_auto"
  ],
  "lines": [
   {
    "id": "gunship_calibrated_04",
    "text": "Gunship calibrated, going auto.",
    "kind": "spoken",
    "duration": 2.571
   },
   {
    "id": "gunship_calibrated_05",
    "text": "The Gunship flies itself now. Guardian Angel.",
    "kind": "spoken",
    "duration": 3.467
   },
   {
    "id": "gunship_calibrated_06",
    "text": "GUNSHIP AUTOPILOT ENGAGED.  SMART TARGETING ON.",
    "kind": "announce",
    "duration": 3.723
   }
  ]
 },
 "canyon_pass": {
  "aliases": [
   "canyon_pass",
   "laser_pass"
  ],
  "note": "(one line only)",
  "lines": [
   {
    "id": "canyon_pass_05",
    "text": "Sol 82 Overhead.  High-power laser.",
    "kind": "spoken",
    "duration": 3.317
   },
   {
    "id": "canyon_pass_06",
    "text": "Light Amplification by Stimulated Emissions of Radiations.",
    "kind": "spoken",
    "duration": 4.181
   },
   {
    "id": "canyon_pass_07",
    "text": "Only ten seconds of concentrated fire.",
    "kind": "spoken",
    "duration": 3.424
   },
   {
    "id": "canyon_pass_04",
    "text": "Sol 82 Overhead.  Light them up.",
    "kind": "spoken",
    "duration": 3.083
   }
  ]
 },
 "sol_firing": {
  "aliases": [
   "SOL FIRING IN 3… 2… 1…"
  ],
  "note": "an automated pass",
  "lines": [
   {
    "id": "sol_firing_01",
    "text": "ORBITAL STRIKE IN 3… 2… light them up!",
    "kind": "countdown",
    "duration": 4.352,
    "beats": [
     1.3563,
     2.3563
    ]
   },
   {
    "id": "sol_firing_05",
    "text": "Sol firing in 3… 2… 1…",
    "kind": "countdown",
    "duration": 3.807,
    "beats": [
     1.111,
     2.111,
     3.111
    ]
   },
   {
    "id": "sol_firing_03",
    "text": "Strike inbound. Three. Two. One.",
    "kind": "countdown",
    "duration": 3.869,
    "beats": [
     1.2226,
     2.2226,
     3.2226
    ]
   },
   {
    "id": "sol_firing_04",
    "text": "Stand clear of the ring. Three… two…",
    "kind": "countdown",
    "duration": 3.189,
    "beats": [
     1.5168,
     2.5168
    ]
   }
  ]
 },
 "laser_calibrated": {
  "aliases": [
   "laser_calibrated",
   "sol88_online"
  ],
  "lines": [
   {
    "id": "laser_calibrated_04",
    "text": "Sol 88 is fully auto.",
    "kind": "spoken",
    "duration": 2.4
   },
   {
    "id": "laser_calibrated_02",
    "text": "SOL-88 is up. It picks its own targets now.",
    "kind": "spoken",
    "duration": 3.915
   },
   {
    "id": "laser_calibrated_03",
    "text": "One more eye in the sky. It doesn't blink.",
    "kind": "spoken",
    "duration": 3.339
   }
  ]
 },
 "sol88_charge": {
  "aliases": [
   "sol88_charge",
   "sol88_away"
  ],
  "note": "(the first launch)",
  "lines": [
   {
    "id": "sol88_charge_01",
    "text": "Charging the rail.",
    "kind": "spoken",
    "duration": 1.653
   },
   {
    "id": "sol88_charge_02",
    "text": "Release!",
    "kind": "spoken",
    "duration": 1.12
   },
   {
    "id": "sol88_charge_05",
    "text": "Launch Successful.  I am good at this.",
    "kind": "spoken",
    "duration": 2.677
   },
   {
    "id": "sol88_charge_04",
    "text": "That's our satellite. First link to the sphere.",
    "kind": "spoken",
    "duration": 3.147
   }
  ]
 },
 "tremor": {
  "aliases": [
   "tremor"
  ],
  "lines": [
   {
    "id": "tremor_04",
    "text": "RADAR SHOWS TREMORS",
    "kind": "announce",
    "duration": 1.76
   },
   {
    "id": "tremor_02",
    "text": "Something's coming up through the ground.",
    "kind": "spoken",
    "duration": 2.315
   },
   {
    "id": "tremor_05",
    "text": "EARTHQUAKE MAGNITUDE 7",
    "kind": "announce",
    "duration": 2.016
   }
  ]
 },
 "first_contact": {
  "aliases": [
   "first_contact"
  ],
  "note": "(new enemy card)",
  "lines": [
   {
    "id": "first_contact_01",
    "text": "New contact.",
    "kind": "spoken",
    "duration": 1.525
   },
   {
    "id": "first_contact_02",
    "text": "Haven't seen that one before.",
    "kind": "spoken",
    "duration": 2.123
   },
   {
    "id": "first_contact_03",
    "text": "Logging it. Don't let it touch you.",
    "kind": "spoken",
    "duration": 2.187
   },
   {
    "id": "first_contact_06",
    "text": "That one can't be rammed. STAY CLEAR.",
    "kind": "spoken",
    "duration": 2.613,
    "qualifier": "solid core"
   },
   {
    "id": "first_contact_07",
    "text": "Soft Target.  Crush it.",
    "kind": "spoken",
    "duration": 1.909,
    "qualifier": "rammable"
   }
  ]
 },
 "stampede_ram_them": {
  "aliases": [
   "STAMPEDE — RAM THEM"
  ],
  "lines": [
   {
    "id": "stampede_ram_them_01",
    "text": "STAMPEDE! Ram them!",
    "kind": "spoken",
    "duration": 1.781
   },
   {
    "id": "stampede_ram_them_02",
    "text": "Floor it. They're soft.",
    "kind": "spoken",
    "duration": 1.824
   },
   {
    "id": "stampede_ram_them_03",
    "text": "Hundreds. All rammable. Go.",
    "kind": "spoken",
    "duration": 2.357
   }
  ]
 },
 "soft_ones_keep_the_chain": {
  "aliases": [
   "SOFT ONES — KEEP THE CHAIN"
  ],
  "lines": [
   {
    "id": "soft_ones_keep_the_chain_04",
    "text": "Soft ones.  Easy Biomass.",
    "kind": "spoken",
    "duration": 2.272
   },
   {
    "id": "soft_ones_keep_the_chain_05",
    "text": "Are you having fun keeping score?",
    "kind": "spoken",
    "duration": 2.379
   },
   {
    "id": "soft_ones_keep_the_chain_03",
    "text": "Pace yourself. They keep coming.",
    "kind": "spoken",
    "duration": 2.315
   }
  ]
 },
 "ram_chain_milestones": {
  "aliases": [
   "ram_chain_milestones"
  ],
  "note": "(RAM ×10, ×25, ×50)",
  "lines": [
   {
    "id": "ram_chain_milestones_01",
    "text": "Ten! Keep going.",
    "kind": "spoken",
    "duration": 1.611
   },
   {
    "id": "ram_chain_milestones_02",
    "text": "Twenty-five. Show-off.",
    "kind": "spoken",
    "duration": 1.888
   },
   {
    "id": "ram_chain_milestones_03",
    "text": "Fifty. I'm writing that down.",
    "kind": "spoken",
    "duration": 2.315
   }
  ]
 },
 "chain_broken": {
  "aliases": [
   "CHAIN BROKEN"
  ],
  "lines": [
   {
    "id": "chain_broken_03",
    "text": "Good run",
    "kind": "spoken",
    "duration": 1.205
   },
   {
    "id": "chain_broken_04",
    "text": "Fun while it lasted.",
    "kind": "spoken",
    "duration": 1.76
   }
  ]
 },
 "gate_half": {
  "aliases": [
   "gate_half"
  ],
  "lines": [
   {
    "id": "gate_half_01",
    "text": "Gate at half.",
    "kind": "spoken",
    "duration": 1.333
   },
   {
    "id": "gate_half_02",
    "text": "The door's taking a beating.",
    "kind": "spoken",
    "duration": 1.931
   }
  ]
 },
 "gate_failing": {
  "aliases": [
   "gate_failing"
  ],
  "lines": [
   {
    "id": "gate_failing_01",
    "text": "Gate failing!",
    "kind": "spoken",
    "duration": 1.397
   },
   {
    "id": "gate_failing_02",
    "text": "The door won't hold much longer.",
    "kind": "spoken",
    "duration": 2.144
   }
  ]
 },
 "gate_broken": {
  "aliases": [
   "gate_broken",
   "THE WALL IS BREACHED"
  ],
  "lines": [
   {
    "id": "gate_broken_01",
    "text": "THE GATE IS DOWN!",
    "kind": "announce",
    "duration": 1.397
   },
   {
    "id": "gate_broken_02",
    "text": "We're open. Push them back.",
    "kind": "spoken",
    "duration": 2.016
   },
   {
    "id": "gate_broken_03",
    "text": "THE WALL IS BREACHED!",
    "kind": "announce",
    "duration": 1.419
   },
   {
    "id": "gate_broken_04",
    "text": "They're through the wall. I'm on my way.",
    "kind": "spoken",
    "duration": 2.613
   },
   {
    "id": "gate_broken_06",
    "text": "PERIMETER BREACH DETECTED!",
    "kind": "announce",
    "duration": 1.952
   }
  ]
 },
 "heart_hit": {
  "aliases": [
   "heart_hit",
   "heart_half",
   "heart_critical"
  ],
  "lines": [
   {
    "id": "heart_hit_01",
    "text": "They're at the heart.",
    "kind": "spoken",
    "duration": 1.632
   },
   {
    "id": "heart_hit_02",
    "text": "Stålheart at half. Get back here.",
    "kind": "spoken",
    "duration": 2.464
   },
   {
    "id": "heart_hit_03",
    "text": "Heart critical! Everything you've got!",
    "kind": "spoken",
    "duration": 2.72
   }
  ]
 },
 "isao_repair": {
  "aliases": [
   "isao_repair"
  ],
  "lines": [
   {
    "id": "isao_repair_01",
    "text": "Going out to patch it.",
    "kind": "spoken",
    "duration": 1.781
   },
   {
    "id": "isao_repair_02",
    "text": "Hold them off. I'm fixing the hole.",
    "kind": "spoken",
    "duration": 2.763
   },
   {
    "id": "isao_repair_03",
    "text": "Repairs. Cover me.",
    "kind": "spoken",
    "duration": 1.653
   }
  ]
 },
 "breach_sealed": {
  "aliases": [
   "BREACH SEALED",
   "STILL OPEN · NEXT SEGMENT"
  ],
  "lines": [
   {
    "id": "breach_sealed_01",
    "text": "Breach sealed.",
    "kind": "spoken",
    "duration": 1.355
   },
   {
    "id": "breach_sealed_02",
    "text": "Holds. Next.",
    "kind": "spoken",
    "duration": 1.419
   },
   {
    "id": "breach_sealed_03",
    "text": "Still open. One more segment.",
    "kind": "spoken",
    "duration": 2.443
   },
   {
    "id": "breach_sealed_05",
    "text": "Fixing Almost AND DONE.",
    "kind": "spoken",
    "duration": 3.02
   }
  ]
 },
 "gate_mended": {
  "aliases": [
   "gate_mended"
  ],
  "lines": [
   {
    "id": "gate_mended_01",
    "text": "Gate's back.",
    "kind": "spoken",
    "duration": 1.291
   },
   {
    "id": "gate_mended_02",
    "text": "Door's whole again.",
    "kind": "spoken",
    "duration": 1.547
   }
  ]
 },
 "sector_brief": {
  "aliases": [
   "sector_brief"
  ],
  "lines": [
   {
    "id": "sector_brief_04",
    "text": "Coming from two sources",
    "kind": "spoken",
    "duration": 1.931
   },
   {
    "id": "sector_brief_02",
    "text": "Close one too early and we lose the biomass.",
    "kind": "spoken",
    "duration": 3.424
   },
   {
    "id": "sector_brief_03",
    "text": "More of them this time. Closer together.",
    "kind": "spoken",
    "duration": 2.848
   }
  ]
 },
 "sector_secure": {
  "aliases": [
   "SECTOR SECURE"
  ],
  "lines": [
   {
    "id": "sector_secure_01",
    "text": "Sector secure.",
    "kind": "spoken",
    "duration": 1.419
   },
   {
    "id": "sector_secure_02",
    "text": "Quiet. For now.",
    "kind": "spoken",
    "duration": 1.589
   },
   {
    "id": "sector_secure_03",
    "text": "That's one. Breathe.",
    "kind": "spoken",
    "duration": 1.675
   }
  ]
 },
 "sector_lost": {
  "aliases": [
   "sector_lost"
  ],
  "lines": [
   {
    "id": "sector_lost_01",
    "text": "We lost it. Regroup.",
    "kind": "spoken",
    "duration": 1.739
   },
   {
    "id": "sector_lost_02",
    "text": "Pull back. Try again.",
    "kind": "spoken",
    "duration": 1.739
   }
  ]
 },
 "back_door": {
  "aliases": [
   "back_door",
   "back_scramble"
  ],
  "lines": [
   {
    "id": "back_door_01",
    "text": "The back! They're coming through the back!",
    "kind": "spoken",
    "duration": 2.272
   },
   {
    "id": "back_door_05",
    "text": "Build defenses behind the bay.",
    "kind": "spoken",
    "duration": 2.272
   },
   {
    "id": "back_door_04",
    "text": "they penetrated the backdoor",
    "kind": "spoken",
    "duration": 2.123
   }
  ]
 },
 "canyon_rises": {
  "aliases": [
   "canyon_rises"
  ],
  "lines": [
   {
    "id": "canyon_rises_01",
    "text": "The far side of the world: a canyon full of them. Hundreds.",
    "kind": "spoken",
    "duration": 4.192
   },
   {
    "id": "canyon_rises_03",
    "text": "All of them in one place.  like fishes in a barrel.",
    "kind": "spoken",
    "duration": 3.659
   }
  ]
 },
 "array_charging": {
  "aliases": [
   "array_charging",
   "array_dry"
  ],
  "note": "shield raised",
  "lines": [
   {
    "id": "array_charging_01",
    "text": "Shield up.",
    "kind": "spoken",
    "duration": 1.227
   },
   {
    "id": "array_charging_02",
    "text": "Charging at the array.",
    "kind": "spoken",
    "duration": 1.824
   },
   {
    "id": "array_charging_03",
    "text": "Array's dry. Ride it out.",
    "kind": "spoken",
    "duration": 2.485
   }
  ]
 },
 "shells_refilled": {
  "aliases": [
   "shells_refilled"
  ],
  "lines": [
   {
    "id": "shells_refilled_01",
    "text": "Shells loaded.",
    "kind": "spoken",
    "duration": 1.376
   },
   {
    "id": "shells_refilled_02",
    "text": "Rack's full.",
    "kind": "spoken",
    "duration": 1.312
   }
  ]
 },
 "plasma_dry": {
  "aliases": [
   "plasma_dry"
  ],
  "note": "(PLASMA DRY)",
  "lines": [
   {
    "id": "plasma_dry_01",
    "text": "Plasma's dry. Find biomass.",
    "kind": "spoken",
    "duration": 2.677
   }
  ]
 },
 "hull_lost": {
  "aliases": [
   "hull_lost"
  ],
  "lines": [
   {
    "id": "hull_lost_01",
    "text": "Hull down. Another one's in the bay.",
    "kind": "spoken",
    "duration": 2.571
   },
   {
    "id": "hull_lost_02",
    "text": "Lost the MÖRK. Next one rolling.",
    "kind": "spoken",
    "duration": 2.784
   }
  ]
 },
 "hull_rebuilt": {
  "aliases": [
   "hull_rebuilt"
  ],
  "lines": [
   {
    "id": "hull_rebuilt_01",
    "text": "New hull. Try to keep this one.",
    "kind": "spoken",
    "duration": 2.315
   }
  ]
 },
 "board_lead": {
  "aliases": [
   "board_lead"
  ],
  "note": "idle at the board",
  "lines": [
   {
    "id": "board_lead_01",
    "text": "Your board. My board. We'll see.",
    "kind": "spoken",
    "duration": 2.208
   },
   {
    "id": "board_lead_02",
    "text": "Zero. For now.",
    "kind": "spoken",
    "duration": 1.717
   },
   {
    "id": "board_lead_03",
    "text": "You're winning. Enjoy it.",
    "kind": "spoken",
    "duration": 1.909
   }
  ]
 },
 "isao_strike_go": {
  "aliases": [
   "isao_strike_go",
   "isao_strike_hit"
  ],
  "note": "Isao's last-ditch missile",
  "lines": [
   {
    "id": "isao_strike_go_01",
    "text": "Hold on. I'm bringing something.",
    "kind": "spoken",
    "duration": 2.379
   },
   {
    "id": "isao_strike_go_02",
    "text": "My turn.",
    "kind": "spoken",
    "duration": 1.312
   },
   {
    "id": "isao_strike_go_03",
    "text": "Last resort. Stand back.",
    "kind": "spoken",
    "duration": 2.251
   },
   {
    "id": "isao_strike_go_07",
    "text": "ONE! Did you see that? MY FIRST ONE!",
    "kind": "spoken",
    "duration": 3.118,
    "qualifier": "on the kill"
   },
   {
    "id": "isao_strike_go_05",
    "text": "Put that on the board.",
    "kind": "spoken",
    "duration": 1.717
   },
   {
    "id": "isao_strike_go_06",
    "text": "Legolas who?",
    "kind": "spoken",
    "duration": 1.355
   }
  ]
 },
 "idle": {
  "aliases": [
   "idle"
  ],
  "note": "(new)",
  "lines": [
   {
    "id": "idle_01",
    "text": "Quiet.",
    "kind": "spoken",
    "duration": 1.035
   },
   {
    "id": "idle_02",
    "text": "Good time to build.",
    "kind": "spoken",
    "duration": 1.632
   },
   {
    "id": "idle_03",
    "text": "The swarm is regrouping. So should we.",
    "kind": "spoken",
    "duration": 2.699
   },
   {
    "id": "idle_06",
    "text": "Every Kilo of Biomass gets us closer to the stars.",
    "kind": "spoken",
    "duration": 4.149
   },
   {
    "id": "idle_05",
    "text": "Somewhere out there, the sphere is waiting.",
    "kind": "spoken",
    "duration": 2.507
   }
  ]
 }
};
