// Generated by `npm run presets -- promote FILE`. Review this content diff before release.
export default {
  "application": "stalheart",
  "audio": {
    "blast_fire": {
      "gain": 0.7,
      "maxVoices": 2,
      "minInterval": 0.14,
      "rateJitter": 0.05
    },
    "boss_tension": {
      "gain": 0.85,
      "maxVoices": 1,
      "minInterval": 20,
      "rateJitter": 0
    },
    "danger_alert": {
      "gain": 1,
      "maxVoices": 1,
      "minInterval": 3,
      "rateJitter": 0
    },
    "enemy_die_a": {
      "gain": 0.6,
      "maxVoices": 3,
      "minInterval": 0.04,
      "rateJitter": 0.12
    },
    "enemy_die_b": {
      "gain": 0.6,
      "maxVoices": 3,
      "minInterval": 0.04,
      "rateJitter": 0.12
    },
    "enemy_die_c": {
      "gain": 0.6,
      "maxVoices": 3,
      "minInterval": 0.04,
      "rateJitter": 0.12
    },
    "field_pulse": {
      "gain": 0.42,
      "maxVoices": 2,
      "minInterval": 0.14,
      "rateJitter": 0.04
    },
    "kinetic_fire": {
      "gain": 0.55,
      "maxVoices": 4,
      "minInterval": 0.06,
      "rateJitter": 0.06
    },
    "laser_click": {
      "gain": 0.5,
      "maxVoices": 1,
      "minInterval": 0.22,
      "rateJitter": 0.06
    },
    "minigun_fire": {
      "gain": 0.22,
      "maxVoices": 5,
      "minInterval": 0.04,
      "rateJitter": 0.07
    },
    "minigun_ready": {
      "gain": 0.42,
      "maxVoices": 1,
      "minInterval": 1.7,
      "rateJitter": 0.02
    },
    "plasma_fire": {
      "gain": 0.4,
      "maxVoices": 3,
      "minInterval": 0.08,
      "rateJitter": 0.03
    },
    "portal_warn": {
      "gain": 0.75,
      "maxVoices": 1,
      "minInterval": 2.5,
      "rateJitter": 0
    },
    "seeker_fire": {
      "gain": 0.5,
      "maxVoices": 3,
      "minInterval": 0.09,
      "rateJitter": 0.05
    },
    "sentry_heptapod": {
      "gain": 0.5,
      "maxVoices": 3,
      "minInterval": 0.09,
      "rateJitter": 0.05
    },
    "sentry_lancer": {
      "gain": 0.4,
      "maxVoices": 3,
      "minInterval": 0.08,
      "rateJitter": 0.03
    },
    "sentry_mortar": {
      "gain": 0.7,
      "maxVoices": 2,
      "minInterval": 0.14,
      "rateJitter": 0.05
    },
    "sentry_needle": {
      "gain": 1,
      "maxVoices": 2,
      "minInterval": 0.1,
      "rateJitter": 0.03
    },
    "sentry_plasma": {
      "gain": 0.4,
      "maxVoices": 3,
      "minInterval": 0.08,
      "rateJitter": 0.03
    },
    "sentry_quiver": {
      "gain": 0.5,
      "maxVoices": 3,
      "minInterval": 0.09,
      "rateJitter": 0.05
    },
    "sentry_relay": {
      "gain": 0.42,
      "maxVoices": 2,
      "minInterval": 0.14,
      "rateJitter": 0.04
    },
    "sentry_rotor": {
      "gain": 0.22,
      "maxVoices": 5,
      "minInterval": 0.04,
      "rateJitter": 0.07
    },
    "server_dialup": {
      "gain": 0.75,
      "maxVoices": 1,
      "minInterval": 8,
      "rateJitter": 0
    },
    "tank_beam": {
      "gain": 0.55,
      "maxVoices": 1,
      "minInterval": 0.2,
      "rateJitter": 0
    },
    "tank_destroyed": {
      "gain": 1,
      "maxVoices": 1,
      "minInterval": 0.5,
      "rateJitter": 0
    },
    "tank_engine": {
      "gain": 0.22,
      "maxVoices": 1,
      "minInterval": 0,
      "rateJitter": 0
    },
    "tank_main": {
      "gain": 1,
      "maxVoices": 2,
      "minInterval": 0.1,
      "rateJitter": 0.03
    },
    "tank_pickup": {
      "gain": 0.65,
      "maxVoices": 2,
      "minInterval": 0.05,
      "rateJitter": 0.04
    },
    "tank_secondary": {
      "gain": 0.3,
      "maxVoices": 3,
      "minInterval": 0.11,
      "rateJitter": 0.1
    },
    "tank_shells": {
      "gain": 0.7,
      "maxVoices": 2,
      "minInterval": 0.05,
      "rateJitter": 0.04
    },
    "tank_spool_down": {
      "gain": 0.5,
      "maxVoices": 1,
      "minInterval": 0.25,
      "rateJitter": 0.03
    },
    "tank_spool_up": {
      "gain": 0.55,
      "maxVoices": 1,
      "minInterval": 0.25,
      "rateJitter": 0.03
    },
    "tank_thruster": {
      "gain": 0.34,
      "maxVoices": 1,
      "minInterval": 0,
      "rateJitter": 0
    },
    "tower_upgrade": {
      "gain": 0.7,
      "maxVoices": 2,
      "minInterval": 0.08,
      "rateJitter": 0
    }
  },
  "base": "stalheart-fx-7",
  "breach": {
    "clearRadius": 6,
    "crackLength": 2,
    "craterRadius": 1,
    "duration": 6.984,
    "fissureArms": 12,
    "fissureWidth": 1.15,
    "look": "tronColors",
    "plateHeave": -0.12,
    "preRoll": 1.6,
    "shrapnelCount": 24
  },
  "id": "baseline",
  "missiles": {
    "heptapod": {
      "aimTolerance": 2.5,
      "duration": 2.7,
      "exhaust": true,
      "length": 0.8,
      "lockBreak": 18,
      "lockGate": 6,
      "lockTime": 1.1,
      "maxRange": 30,
      "mesh": "dart",
      "minRange": 3,
      "profile": "hook"
    },
    "quiver": {
      "aimTolerance": 2.5,
      "duration": 1.35,
      "exhaust": true,
      "length": 0.32,
      "lockBreak": 18,
      "lockGate": 6,
      "lockTime": 1.1,
      "maxRange": 30,
      "mesh": "dart",
      "minRange": 3,
      "profile": "swift"
    }
  },
  "schema": 1,
  "weapons": {
    "heptapod": {
      "impact": {
        "colors": {
          "spark": 16757854
        },
        "recipe": "shell",
        "size": 1,
        "tune": {}
      },
      "muzzle": {
        "colors": {
          "ember": 16751196,
          "flash": 16765088
        },
        "recipe": [
          "flash",
          "ember"
        ],
        "size": 0.7,
        "tune": {
          "emberCount": 22
        }
      },
      "shot": {
        "kind": "seeker",
        "projPx": 6,
        "projSpeed": 12,
        "trail": 7
      }
    },
    "lancer": {
      "impact": {
        "colors": {
          "ember": 12124112,
          "spark": 5111686,
          "splash": 5111686
        },
        "recipe": [
          "spark",
          "flash",
          "ember"
        ],
        "size": 0.7,
        "tune": {
          "debrisSpeed": 3.9,
          "emberCount": 20,
          "emberDrag": 0.55,
          "emberLife": 1,
          "emberRise": 1,
          "flashLife": 0.1,
          "flashRings": 1,
          "flashSize": 0.05,
          "ringEnd": 0.2,
          "ringWidth": 0.01,
          "scorchSize": 0.05,
          "sparkBounce": 0,
          "sparkCount": 20,
          "sparkGravity": 20,
          "sparkSize": 1,
          "sparkSpeed": 3,
          "sparkSpread": 0.45,
          "splashCling": 1,
          "splashCount": 90,
          "splashLife": 4.9,
          "splashSag": 12
        }
      },
      "muzzle": {
        "colors": {
          "flash": 5111686
        },
        "recipe": [
          "flash"
        ],
        "size": 0.45,
        "tune": {
          "flashLife": 0.1
        }
      },
      "shot": {
        "beamColor": 5111686,
        "kind": "lance",
        "projPx": 7,
        "projSpeed": 42,
        "trail": 11
      }
    },
    "mortar": {
      "impact": {
        "colors": {
          "spark": 16756838
        },
        "recipe": "shell",
        "size": 1.25,
        "tune": {
          "debrisCount": 14,
          "ringEnd": 0.95
        }
      },
      "muzzle": {
        "colors": {
          "ember": 16747076,
          "flash": 16767392
        },
        "recipe": [
          "flash",
          "ember"
        ],
        "size": 0.95,
        "tune": {
          "emberCount": 24
        }
      },
      "shot": {
        "kind": "lob",
        "projPx": 12,
        "projSpeed": 3.5,
        "trail": 6
      }
    },
    "needle": {
      "impact": {
        "colors": {
          "spark": 13232895
        },
        "recipe": [
          "spark",
          "flash",
          "debris"
        ],
        "size": 0.85,
        "tune": {
          "debrisCount": 8,
          "ringEnd": 0.2
        }
      },
      "muzzle": {
        "colors": {
          "flash": 15267583,
          "spark": 12182783
        },
        "recipe": [
          "flash",
          "spark"
        ],
        "size": 0.55,
        "tune": {
          "flashLife": 0.08,
          "sparkCount": 12
        }
      },
      "shot": {
        "kind": "round",
        "projPx": 9,
        "projSpeed": 100,
        "trail": 8
      }
    },
    "plasma": {
      "impact": {
        "colors": {
          "ember": 8388592,
          "splash": 3139280
        },
        "recipe": "plasma",
        "size": 0.75,
        "tune": {}
      },
      "muzzle": {
        "colors": {
          "ember": 3139280,
          "flash": 3139280
        },
        "recipe": [
          "flash",
          "ember"
        ],
        "size": 0.5,
        "tune": {}
      },
      "shot": {
        "kind": "throw",
        "plasma": true,
        "projPx": 0,
        "projSpeed": 0,
        "trail": 0
      }
    },
    "quiver": {
      "impact": {
        "colors": {
          "spark": 10339583
        },
        "recipe": "shell",
        "size": 1,
        "tune": {
          "ringEnd": 0.8
        }
      },
      "muzzle": {
        "colors": {
          "ember": 16751196,
          "flash": 14674175
        },
        "recipe": [
          "flash",
          "ember"
        ],
        "size": 0.75,
        "tune": {
          "emberCount": 26,
          "emberLife": 2.4
        }
      },
      "shot": {
        "kind": "seeker",
        "projPx": 5,
        "projSpeed": 13,
        "trail": 6
      }
    },
    "relay": {
      "impact": {
        "colors": {},
        "recipe": [],
        "size": 0,
        "tune": {}
      },
      "muzzle": {
        "colors": {},
        "recipe": [],
        "size": 0,
        "tune": {}
      },
      "shot": {
        "kind": "field",
        "projPx": 0,
        "projSpeed": 0,
        "trail": 0
      }
    },
    "rotor": {
      "impact": {
        "colors": {
          "spark": 16765066
        },
        "recipe": "light",
        "size": 0.45,
        "tune": {}
      },
      "muzzle": {
        "colors": {
          "flash": 16770216
        },
        "recipe": "light",
        "size": 0.3,
        "tune": {
          "flashLife": 0.06,
          "sparkCount": 10
        }
      },
      "shot": {
        "kind": "round",
        "projPx": 4,
        "projSpeed": 24,
        "trail": 2
      }
    }
  }
};
