import * as THREE from '../../vendor/three.module.js';
import { stepYardDrive } from '../domain/yard-drive.js';
import { makeTankFeel,stepTankFeel,applyTankFeel } from '../tankfeel.js';
import { FEEL,loadFeel } from '../feelstore.js';
export function createAstroDrive(root,{camera,controls,getTank,obstacles}){
 const events=new AbortController(),keys=new Set(),feel=makeTankFeel(),state={x:0,z:0,yaw:0,speed:0,blocked:false};loadFeel();
 let mode='free',active=false,attached=null,base=null,radius=5,freeView=null,followDistance=24;
 const ui=document.createElement('div');ui.className='astro-drive';Object.assign(ui.style,{position:'absolute',bottom:'42px',left:'18px',zIndex:6,color:'#d6f4f7',background:'#061116e8',padding:'10px',font:'12px monospace'});ui.innerHTML='<button data-view="free">1 · Free camera</button> <button data-view="tank">3 · Drive MÖRK</button><div data-drive-status></div><div data-pad hidden><button data-key="w">↑</button> <button data-key="a">←</button> <button data-key="s">↓</button> <button data-key="d">→</button></div>';root.append(ui);
 function clear(){keys.clear();state.speed=0;}
 function setMode(value){if(value===mode)return;if(value==='tank'&&!getTank())return;clear();if(value==='tank'){freeView={position:camera.position.clone(),target:controls.target.clone()};mode='tank';controls.enabled=false;follow(1);}else{mode='free';controls.enabled=true;if(freeView){camera.position.copy(freeView.position);controls.target.copy(freeView.target);controls.update();}}ui.querySelector('[data-pad]').hidden=mode!=='tank';}
 ui.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){setMode(b.dataset.view);b.blur();}},{signal:events.signal});
 for(const b of ui.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(mode==='tank')keys.add(b.dataset.key);},{signal:events.signal});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key),{signal:events.signal});}
 const typing=e=>e.target.closest?.('input,select,textarea,[contenteditable="true"]');
 window.addEventListener('keydown',e=>{if(!active||typing(e))return;const k=e.key.toLowerCase();if(k==='1'||k==='3'){e.preventDefault();setMode(k==='1'?'free':'tank');return;}const mapped=({arrowup:'w',arrowdown:'s',arrowleft:'a',arrowright:'d'})[k]||k;if(mode==='tank'&&['w','a','s','d'].includes(mapped)){e.preventDefault();keys.add(mapped);}},{signal:events.signal});
 window.addEventListener('keyup',e=>{keys.delete(({ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'})[e.key]||e.key.toLowerCase());},{signal:events.signal});window.addEventListener('blur',clear,{signal:events.signal});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();},{signal:events.signal});
 root.querySelector('canvas').addEventListener('wheel',e=>{if(mode!=='tank'||!active)return;e.preventDefault();followDistance=THREE.MathUtils.clamp(followDistance+e.deltaY*.02,12,60);},{passive:false,signal:events.signal});
 function attach(){const tank=getTank();if(!tank)return null;if(attached!==tank){attached=tank;base=tank.position.clone();state.x=base.x;state.z=base.z;state.yaw=tank.rotation.y;const size=new THREE.Box3().setFromObject(tank).getSize(new THREE.Vector3());radius=Math.hypot(size.x,size.z)*.5;}return tank;}
 function follow(alpha){const tank=attach();if(!tank)return;const forward=new THREE.Vector3(Math.sin(state.yaw),0,Math.cos(state.yaw)),target=tank.position.clone().addScaledVector(forward,9);target.y+=3;const eye=tank.position.clone().addScaledVector(forward,-followDistance);eye.y+=followDistance*.5;camera.position.lerp(eye,alpha);camera.lookAt(target);}
 return {setMode,resize(){attached=null;clear();attach();},setActive(on){active=on;if(!on)clear();},tick(dt){const tank=attach();if(!tank)return;if(mode==='tank'&&active){stepYardDrive(state,{throttle:Number(keys.has('w'))-Number(keys.has('s')),turn:Number(keys.has('a'))-Number(keys.has('d'))},dt,obstacles(),radius);tank.position.set(state.x,base.y,state.z);tank.rotation.y=state.yaw;}stepTankFeel(feel,dt,mode==='tank'&&active,FEEL);applyTankFeel(tank,feel,FEEL);if(mode==='tank')follow(1-Math.exp(-dt*8));ui.querySelector('[data-drive-status]').textContent=mode==='tank'?`WASD / arrows · ${Math.abs(state.speed).toFixed(1)} m/s${state.blocked?' · structure ahead':''} · wheel: zoom`:'Orbit / pan / zoom · tank parked';},
 state:()=>({mode,...state,camera:camera.position.toArray(),hover:feel.hoverT,keys:keys.size}),dispose(){events.abort();clear();ui.remove();controls.enabled=true;}};
}
