// Keys match controller properties, so changing a display label keeps its help.
export const SENTRY_HELP = Object.freeze({
  family: 'Choose the numbered Sentry model for the entire battery. You can also click a tower to use the radial picker.',
  tier: 'Load tier 1, 2 or 3 of the selected Sentry model. This changes its model and muzzle layout; the lab’s firing knobs stay as set.',
  mode: 'Waves sends walkers toward the battery. Pop presents temporary targets around the range. Changing mode resets the range.',
  live: 'Run target movement and allow new shots. Turning this off freezes targets and stops new shots; aiming and shots already in flight continue.',
  autoFire: 'Allow Sentries to fire automatically when their aim, cooldown and missile lock are ready. Turn off to watch tracking without new shots.',
  manual: 'Use the manual yaw and elevation settings instead of tracking targets. Fixed launchers stay fixed; missiles still need a target lock to fire.',
  yaw: 'Horizontal aiming angle in degrees when driving by hand. Automatic tracking chooses this angle when manual aim is off.',
  elev: 'Upward or downward aiming angle in degrees when driving by hand. Positive angles lift the barrel; the elevation stops still apply.',
  count: 'Number of Sentries in the battery. Each aims independently, but all use the selected family and tier. Changing this rebuilds the battery.',
  spread: 'Radius of the ring holding a battery of multiple Sentries, in range units. Larger values spread them farther from the center. A single Sentry stays centered.',
  mount: 'Height of the Sentry bases above the ground, in range units. Raising them changes firing geometry and can create a blind area below direct-fire guns.',
  walls: 'Show or hide the wall beneath raised Sentries. Hiding it does not lower the Sentries or change their firing geometry.',
  sound: 'Enable the Sentries’ firing and ready sounds in this lab. Browser audio starts after an interaction.',
  yawRate: 'Maximum horizontal turning speed, in degrees per second. Higher values let an articulated turret catch a new target sooner.',
  pitchRate: 'Maximum upward/downward turning speed, in degrees per second. Fixed vertical launch tubes do not tilt.',
  tolerance: 'Maximum aim error in degrees at which the gun may fire. A smaller value demands more precise alignment; missiles also require a lock.',
  elevMin: 'Lowest aiming angle for direct-fire guns, in degrees. More negative values allow deeper downward aim and reduce blind areas near raised Sentries.',
  elevMax: 'Highest aiming angle allowed by the normal turret drive, in degrees. Lobbers use a separate 85° ceiling; fixed launch tubes retain their authored direction.',
  cooldown: 'Preview-only minimum seconds between shots from each Sentry; gameplay retains its weapon cadence and cassette rules. Lower values allow faster firing, but aim and missile-lock requirements can still delay the next shot.',
  recoilKick: 'Distance the recoil pivot moves backward when firing, in model units. This changes the visible kick, not damage or rocket flight.',
  recoilBack: 'Speed at which the recoil pivot returns to rest, in model units per second. Higher values recover faster.',
  minRange: 'Minimum engagement distance in meters along the ground from each Sentry. Closer targets are ignored: no acquisition, lock or new shot. A target moving inside this limit is dropped immediately; rockets already launched continue. Cannot exceed the maximum. Quiver and Heptapod have separate saved settings.',
  maxRange: 'Base maximum acquisition distance in meters along the ground from each Sentry. Each equipment upgrade adds the same 8% range bonus in lab and game. Ten meters equals one board cell; model size does not affect reach. Farther targets are ignored and any current lock on them is cleared. Cannot be smaller than the minimum. Range / farthest controls target spawning separately. Quiver and Heptapod have separate saved settings.',
  lockGate: 'Aim error in degrees within which a missile lock can build. Outside this gate, an unfinished lock loses progress. Saved separately for Quiver and Heptapod and applied in both lab and game.',
  lockTime: 'Seconds of tracking inside the lock gate needed to acquire a missile lock. The launcher clears its lock after each shot.',
  lockBreak: 'Aim error in degrees above which an acquired missile lock breaks. Losing or changing the target also breaks it. This affects the launcher’s lock, not a rocket already in flight.',
  profile: 'Choose the authored rocket motion: Swift, Hook or Heavy. Selecting one also sets its native duration to 1.35, 2.7 or 4 seconds. Quiver and Heptapod only.',
  duration: 'Total rocket flight time in seconds for new shots. Lower values play the selected motion faster. This is a Sentry-lab preview setting.',
  length: 'Nominal rocket body length in meters. Larger values make the same low-triangle DART mesh appear bigger. New shots use the new size.',
  exhaust: 'Show the rocket’s exhaust during the powered part of its flight. It remains off before ignition and at arrival. Quiver and Heptapod only.',
  muzzleVel: 'Projectile speed in range units per second, also used to estimate target lead. DART flight time is controlled separately by missile duration.',
  lead: 'Aim ahead of moving targets using their velocity and the muzzle-velocity setting. This helps direct shots intercept walkers rather than chase their current position.',
  waveSize: 'Number of walkers in the first wave. Applies in Waves mode; reset the range to restart from wave one.',
  waveGrow: 'Extra walkers added on each successive wave. For example, a first wave of 6 and growth of 2 produces waves of 6, 8, 10 and so on.',
  waveGap: 'Wait in seconds after a wave is cleared or gets through before the next wave starts. Applies in Waves mode.',
  walkSpeed: 'Base inward speed of walkers, in range units per second. Individual walkers vary slightly. New walkers receive the updated speed when spawned.',
  reachRadius: 'Distance from the center of the battery at which a walker counts as having got through. It is removed and the “through” counter increases. A larger value lets walkers escape sooner. Waves mode only.',
  targets: 'Number of temporary targets maintained around the range in Pop mode. Missing or expired targets are replenished.',
  hp: 'Hits needed to defeat each newly spawned target. Existing targets keep their remaining health; reset the range for an immediate fresh test.',
  popMin: 'Minimum base time in seconds for a Pop target to stay up. Its actual lifetime is randomized between the minimum and maximum, with refill staggering added.',
  popMax: 'Maximum base time in seconds for a Pop target to stay up. Targets drop after their lifetime even if no Sentry hits them.',
  ringMin: 'Inner radius for spawning Pop targets, in range units from the center. This does not set a weapon’s minimum firing range.',
  ringMax: 'Outer radius for Pop targets and approximate spawn radius for incoming waves, in range units. Also scales the displayed range and lob arcs.',
  targetHi: 'Maximum height above the floor for newly spawned Pop targets, in range units. Waves remain on the ground.',
  seed: 'Seed for repeatable target layouts and timing. Changing it resets the range; the same seed and settings reproduce the same random sequence.',
  again: 'Clear targets, shots and range statistics, then restart with the current seed and settings. This also returns active rockets to their pool.',
  wire: 'Show or hide the floor’s wire grid. This only changes the range display.',
  tracers: 'Show or hide the projectile and rocket meshes. Shots still travel and register hits; beams and impact effects remain visible.',
  recentre: 'Move the camera back to the standard view of the battery and range. This does not reset the targets or settings.',
});
