// One immutable JSON file per entry. No append collisions, no role/index copies.
import { readFileSync, readdirSync, mkdirSync, writeFileSync, renameSync, unlinkSync, linkSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
export const logDir = resolve(root, 'docs/log/entries');
export function validateEntry(e) {
  if (e?.schema !== 1 || !/^[a-z0-9][a-z0-9-]{0,100}$/.test(e.id || '')) throw Error('Invalid log schema/id');
  if (!['decision','change','experiment','issue'].includes(e.type)) throw Error('Invalid entry type');
  if (!['accepted','proposed','observed','resolved'].includes(e.status)) throw Error('Invalid status');
  if (e.type === 'decision' && !['accepted','proposed'].includes(e.status)) throw Error('Decisions must be accepted or proposed');
  if (!Number.isFinite(Date.parse(e.date))) throw Error('Invalid date');
  for (const key of ['title','context','outcome']) if (typeof e[key] !== 'string' || !e[key].trim()) throw Error(`Missing ${key}`);
  for (const key of ['evidence','alternatives','supersedes']) if (!Array.isArray(e[key]) || !e[key].every(x => typeof x === 'string')) throw Error(`Invalid ${key}`);
  if (JSON.stringify(e).length > 40000) throw Error('Entry too large; link supporting artifacts');
  return e;
}
export function readEntries(dir = logDir) {
  const entries = readdirSync(dir).filter(n => n.endsWith('.json')).map(n => {
    const e = validateEntry(JSON.parse(readFileSync(resolve(dir,n),'utf8')));
    if (n !== `${e.id}.json`) throw Error(`Entry filename differs from id: ${n}`);
    return e;
  }).sort((a,b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id));
  const byId = new Map(entries.map(e => [e.id,e]));
  for (const e of entries) for (const id of e.supersedes) {
    if (!byId.has(id) || id === e.id) throw Error(`Unknown/self supersedes: ${id}`);
    const seen = new Set([e.id]);
    function visit(k) { if (seen.has(k)) throw Error('Supersedes cycle'); seen.add(k); for(const p of byId.get(k).supersedes) visit(p); seen.delete(k); }
    visit(id);
  }
  return entries;
}
export function appendEntry(entry, dir = logDir) {
  const e = validateEntry(entry); mkdirSync(dir,{recursive:true});
  const existing = readEntries(dir);
  if (existing.some(x => x.id === e.id)) throw Error('Entry already exists; add a superseding entry');
  for (const id of e.supersedes) if (!existing.some(x => x.id === id)) throw Error(`Unknown supersedes id: ${id}`);
  // An exclusive final write fails instead of overwriting concurrent work.
  const temp = resolve(dir, `.${randomUUID()}.tmp`);
  try {
    writeFileSync(temp, JSON.stringify(e,null,2)+'\n', { flag:'wx' });
    linkSync(temp, resolve(dir,`${e.id}.json`));
  } finally { try { unlinkSync(temp); } catch {} }
}
function renderedLog(entries) {
  const playfeel = (() => { try { return readFileSync(resolve(root,'docs/PLAYFEEL.md'),'utf8'); } catch { return ''; } })();   // the owner's playtest notes, rendered as their own section
  const text = '# Stalheart development log\n\nGenerated by `npm run log -- render`. Canonical entries: `docs/log/entries/`.\n\n'+entries.slice().reverse().map(e =>
    `## ${e.date.slice(0,10)} — ${e.title}\n\n${e.type} · ${e.status} · ${e.id}\n\n${e.context}\n\n${e.outcome}\n\n`+
    (e.alternatives.length ? `Alternatives: ${e.alternatives.join('; ')}\n\n` : '')+
    (e.evidence.length ? `Evidence:\n\n${e.evidence.map(x=>'- '+x).join('\n')}\n\n` : '')+
    (e.supersedes.length ? `Supersedes: ${e.supersedes.join(', ')}\n\n` : '')).join('')+(playfeel ? '\n---\n\n' + playfeel.replace(/^# /, '## ') : '');
  return text.trimEnd() + '\n';
}
function render(entries) {
  const text=renderedLog(entries);
  const path=resolve(root,'DEVLOG.md'),tmp=path+`.${randomUUID()}.tmp`;
  try { writeFileSync(tmp,text); renameSync(tmp,path); } finally { try { unlinkSync(tmp); } catch {} }
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const [cmd='check',file] = process.argv.slice(2);
    if(cmd==='add') { if(!file)throw Error('Usage: log.mjs add entry.json');appendEntry(JSON.parse(readFileSync(file,'utf8'))); }
    else if(!['check','render'].includes(cmd))throw Error('Use add FILE, check, or render');
    const entries=readEntries(); if(cmd!=='check')render(entries);
    else if (readFileSync(resolve(root,'DEVLOG.md'),'utf8') !== renderedLog(entries)) throw Error('DEVLOG is stale; run npm run log -- render');
    console.log(`${entries.length} valid Stalheart log entries.`);
  } catch(e) { console.error(e.message);process.exit(1); }
}
