// Shared by the CLI and local authoring service. Read generated data, never eval it.
import { readFile, writeFile, rename, mkdir, unlink, readdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { baselinePreset, parsePreset, serializePreset } from '../src/content/preset.js';
export const digest = text => createHash('sha256').update(text).digest('hex');
export const shippedPath = root => resolve(root, 'src/content/shipped.js');
export function decodeShipped(source) {
  const match = source.replace(/^\s*\/\/[^\n]*(?:\n|$)/, '').trim().match(/^export default ([\s\S]*);$/);
  if (!match) throw Error('shipped.js is not a generated data module; refusing to overwrite it.');
  return match[1].trim() === 'null' ? baselinePreset() : parsePreset(match[1]);
}
export const encodeShipped = preset => '// Generated by `npm run presets -- promote FILE`. Review this content diff before release.\nexport default ' + serializePreset(preset).trimEnd() + ';\n';
export async function readShipped(root) {
  const source = await readFile(shippedPath(root), 'utf8');
  return { source, preset: decodeShipped(source), revision: digest(source) };
}
export async function atomicWrite(path, text) {
  await mkdir(dirname(path), { recursive: true });
  const temp = path + `.${randomUUID()}.tmp`;
  try { await writeFile(temp, text, { flag: 'wx' }); await rename(temp, path); }
  finally { await unlink(temp).catch(() => {}); }
}
export async function withPromotionLock(root, run) {
  const path = resolve(root, 'artifacts/authoring/promotion.lock');
  await mkdir(dirname(path), { recursive: true });
  try { await writeFile(path, JSON.stringify({ pid: process.pid }), { flag: 'wx' }); }
  catch (error) {
    if (error.code !== 'EEXIST') throw error;
    // A crashed process leaves a recoverable lock. A live process always wins.
    let owner; try { owner = JSON.parse(await readFile(path, 'utf8')).pid; } catch {}
    if (Number.isInteger(owner) && owner > 0) {
      try { process.kill(owner, 0); } catch (e) {
        if (e.code === 'ESRCH') { await unlink(path); return withPromotionLock(root, run); }
      }
    }
    throw Error('Another promotion is running. Try again after it finishes.');
  }
  try { return await run(); } finally { await unlink(path); }
}
export async function promotePreset(root, preset, { expectedRevision, validate = async () => {}, subject = null, source, operation = 'apply' } = {}) {
  // The caller holds the lock through validation and any rollback.
  const before = await readShipped(root);
  if (expectedRevision && before.revision !== expectedRevision) throw Error('Defaults changed after review. Review again before applying.');
  const next = source ?? encodeShipped(preset);
  decodeShipped(next);
  if (next === before.source) return { ...before, receipt: null, unchanged: true };
  const id = `${Date.now()}-${randomUUID()}`;
  const receipt = { schema: 1, id, operation, subject, before: before.source, after: next, beforeRevision: before.revision, afterRevision: digest(next) };
  // Persist recovery data before changing source; interrupted writes remain auditable.
  await atomicWrite(resolve(root, `artifacts/authoring/history/${id}.json`), JSON.stringify(receipt, null, 2) + '\n');
  await atomicWrite(shippedPath(root), next);
  try { await validate(); }
  catch (error) {
    if ((await readShipped(root)).revision === receipt.afterRevision) {
      await atomicWrite(shippedPath(root), before.source);
      await atomicWrite(resolve(root, `artifacts/authoring/history/${id}.failed.json`), JSON.stringify({ error: error.message }));
      throw Error(`Validation failed; previous defaults restored. ${error.message}`);
    }
    throw Error(`Validation failed and defaults changed externally; recovery is in artifacts/authoring/history/${id}.json. ${error.message}`);
  }
  return { ...await readShipped(root), receipt: { id, subject, operation } };
}
export async function latestUndo(root, revision) {
  const dir = resolve(root, 'artifacts/authoring/history');
  const files = await readdir(dir).catch(e => { if (e.code === 'ENOENT') return []; throw e; });
  for (const file of files.filter(f => f.endsWith('.json') && !f.endsWith('.failed.json')).sort().reverse()) {
    const item = JSON.parse(await readFile(resolve(dir, file), 'utf8'));
    if (item.operation === 'apply' && item.afterRevision === revision && !files.includes(file.replace('.json', '.failed.json'))) return item;
  }
  return null;
}
